# Includes
gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Clumpy
tagline:          'Sharing the things that stick'
description:      "We read a lot. When we find something that makes us think, we'll share it with you."
url:              http://clumpy.io
baseurl:          /

author:
  name:           'James Thompson and Tanner Stirrat'

paginate:         5

# Custom vars
version:          2.1.0
